name: Abhishek Garg
bio: 'Proud Indian, love bash and making stuff out of this'
picture: 'assets/images/profile.jpg'

permalink: /:title/

analytics: 'UA-72416277-1'
#disqus: mydisqus
#instagram: myinstagram
#youtube: myyoutube
#spotify: myspotify
facebook: g.abhish
twitter: _AbhishekGarg
linkedin: in/abhishgarg
github: abhishgarg
email: hello@abhishekgarg.xyz

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

markdown: kramdown
highlighter: pygments

kramdown:
    input: GFM
    hard_wrap: false

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
