# Site settings
title: Abhishek Garg
description: 'Technologist and a Proud Indian, love to learn something daily and making stuff'
url: 'http://abhishekgarg.xyz'
baseurl: '/'
google_analytics: 'UA-72416277-1'

author:
  name: 'Abhishek Garg'
  email: hello@abhishekgarg.xyz
  twitter_username: _AbhishekGarg
#  github_username:  joshgerdes
  linkedin_username:  abhishgarg

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems:
  - jemoji

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
